### ISSUE TITLE
Thoughts on using ipfs over firebase? 

### ISSUE THREAD

**Issue by RusseII** [actuallymentor/rocketeer#1]
https://ethereum.org/en/developers/docs/storage/#additional-consideration
https://infura.io/product/ipfs

I'll look into making a PR if there's interest.

**Comment by RusseII** [comment]
https://docs.ipfs.io/how-to/best-practices-for-nft-data/
https://docs.ipfs.io/how-to/mint-nfts-with-ipfs/

**Comment by actuallymentor** [comment]
I like the thought, but it is low priority for this usecase :)
